all:
	@javac *.java -cp "lib/*" -Xlint:none
#	java FreeBaseSearch -cp httpclient-4.3.3.jar;httpclient-cache-4.3.3.jar;httpcore-4.3.2.jar;httpmime-4.3.3.jar;jackson-annotations-2.2.3.jar;jackson-core-2.2.3.jar;jackson-databind-2.2.3.jar;json-path-0.9.0.jar;json-simple-1.1.1.jar
	$(info Source compiled. Please run as: java -cp ".:lib/*" FreeBaseSearch <parameters>)
	$(info The parameters follow the standard of the reference implementation)
	$(info )
	
	